spring:
  datasource:
    url: jdbc:mysql://47.100.29.122:3306/data1?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
    username: data1
    password: GTFSMJYPKXY4TxiN
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: localhost
    port: 6379
    password: 123456


logging:
  level:
    com:
      liao:
        iot: debug
  file: log/log-debug.log

