spring:
  datasource:
    url: jdbc:mysql://47.100.29.122:3306/data1?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT
    username: data1
    password: GTFSMJYPKXY4TxiN
    driver-class-name: com.mysql.cj.jdbc.Driver
  swagger:
    base-package: com.liao
    enabled: true

#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    password: 123456


logging:
  level:
    com:
      liao:
        insurance: debug
# 取消日志文件的文本记录
#  file: log/log-debug.log

